version: "3.9"
services:
  admin-db:
    image: postgres:16.1-bullseye
    container_name: database
    ports:
      - "9000:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
volumes:
    pgdata:
    

